apiVersion: v1
kind: ServiceAccount
metadata:
  name: trivial-service-account
  namespace: argocd
imagePullSecrets:
  - name: trivial-access-token

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivial-deployment
  namespace: argocd
  labels:
    app: trivial-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trivial-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: trivial-app
    spec:
      serviceAccountName: trivial-service-account
      imagePullSecrets:
        - name: trivial-access-token
      initContainers:
        - name: fix-permission
          image: busybox
          command: ['sh', '-c', 'mkdir -p /var/cache/nginx/client_temp && chmod -R 777 /var/cache/nginx']
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
      containers:
        - name: coco
          image: shadowhub/cocomaster:20240506044802
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 64m
              memory: 25Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 5
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
      volumes:
        - name: nginx-cache
          emptyDir: {}
