apiVersion: v1
kind: Secret
metadata:
  name: trivial-access-token
  namespace: argocd
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth": "c2hhZG93aHViOmRja3JfcGF0X19OR1MtT3hCM2RpejEySV9GaTdlclJseTc2QQ=="
        }
      }
    }