name: Deployment

on:
    push:
        branches:
            - master
    pull_request:

permissions:
    id-token: write
    contents: read

jobs:
  skaffold:
    name: 'Skaffold'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install kustomize'
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        sudo mv kustomize /usr/local/bin

    - name: 'Download Skaffold'
      run: |
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
        chmod +x skaffold
        sudo mv skaffold /usr/local/bin/

    - name: 'Verify Skaffold Installation'
      run: |
        echo "Skaffold location: $(which skaffold)"
        echo "Skaffold file type: $(file /usr/local/bin/skaffold)"
        echo "Skaffold version:"
        skaffold version || echo "Failed to get version"
        echo "Skaffold help:"
        skaffold --help || echo "Failed to get help"

    - name: Remove Existing Skaffold Config
      run: |
        if [ -f "skaffold.yaml" ]; then
        rm skaffold.yaml
        echo "Removed existing skaffold.yaml."
        fi
      
    - name: Skaffold Initialization
      run: skaffold init --skip-build --force
      

    - name: Build Artifact
      run: skaffold build --manifests.kustomize.paths=overlay/dev
