name: Deployment

on:
    push:
        branches:
            - master
    pull_request:

permissions:
    id-token: write
    contents: read

jobs:
    scaffold:
        name: 'scaffold'
        runs-on: ubuntu-latest

        steps:
        - name: 'Checkout'
          uses: actions/checkout@v2

        - name: 'Install kustomize'
          run: |
            curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
            sudo mv kustomize /usr/local/bin

        - name: 'Check for Scaffold in repository'
          run: |
            if [ -f "./scaffold" ]; then
              echo "Scaffold found in repository"
              chmod +x ./scaffold
              sudo mv ./scaffold /usr/local/bin/
            else
              echo "Scaffold not found in repository"
              echo "Please add the Scaffold binary to your repository or provide the correct download URL"
              exit 1
            fi

        - name: 'Verify Scaffold Installation'
          run: |
            echo "Scaffold location: $(which scaffold)"
            echo "Scaffold file type: $(file /usr/local/bin/scaffold)"
            echo "Scaffold version:"
            scaffold --version || echo "Failed to get version"
            echo "Scaffold help:"
            scaffold --help || echo "Failed to get help"

        - name: Scaffold Initialization
          run: scaffold init --skip-build

        - name: Build Artifact
          run: scaffold build --manifests.kustomize.paths=overlay/dev