name: Deployment

on:
    push:
        branches:
            - master
    pull_request:

permissions:
    id-token: write
    contents: read

jobs:
    scaffold:
        name: 'scaffold'
        runs-on: ubuntu-latest

        steps:
        - name: 'Checkout'
          uses: actions/checkout@v2

        - name: 'Install kustomize'
          run: |
            curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
            sudo mv kustomize /usr/local/bin

        - name: 'Install Scaffold'
          run: | 
            echo "Current directory: $(pwd)"
            echo "Downloading Scaffold..."
            curl -L https://github.com/scaffold/scaffold/releases/latest/download/scaffold-linux-amd64 -o scaffold
            echo "Download complete. File size: $(wc -c < scaffold) bytes"
            echo "File contents:"
            cat scaffold
            echo "Making scaffold executable..."
            chmod +x scaffold
            echo "Moving scaffold to /usr/local/bin..."
            sudo mv scaffold /usr/local/bin
            echo "Installation complete"

        - name: 'Verify Scaffold Installation'
          run: |
            echo "Scaffold location: $(which scaffold)"
            echo "Scaffold file type: $(file /usr/local/bin/scaffold)"
            echo "Scaffold version:"
            scaffold --version || echo "Failed to get version"
            echo "Scaffold help:"
            scaffold --help || echo "Failed to get help"

        - name: Scaffold Initialization
          run: |
            echo "Running scaffold init --skip-build"
            scaffold init --skip-build
          continue-on-error: true

        - name: Build Artifact
          run: |
            echo "Running scaffold build"
            scaffold build --manifests.kustomize.paths=overlay/dev
          continue-on-error: true