name: Deployment

on:
    push:
        branches:
            - master
    pull_request:

permissions:
    id-token: write
    contents: read

jobs:
  skaffold:
    name: 'Skaffold'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install kustomize'
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        sudo mv kustomize /usr/local/bin

    - name: 'Install conntrack and crictl'
      run: |
        sudo apt-get update
        sudo apt-get install -y conntrack
        VERSION="v1.24.2"
        curl -L https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/crictl-$VERSION-linux-amd64.tar.gz --output crictl-$VERSION-linux-amd64.tar.gz
        sudo tar zxvf crictl-$VERSION-linux-amd64.tar.gz -C /usr/local/bin
        rm -f crictl-$VERSION-linux-amd64.tar.gz

    - name: 'Install cri-dockerd'
      run: |
        VER=$(curl -s https://api.github.com/repos/Mirantis/cri-dockerd/releases/latest|grep tag_name | cut -d '"' -f 4|sed 's/v//g')
        wget https://github.com/Mirantis/cri-dockerd/releases/download/v${VER}/cri-dockerd-${VER}.amd64.tgz
        tar xvf cri-dockerd-${VER}.amd64.tgz
        sudo mv cri-dockerd/cri-dockerd /usr/local/bin/
        wget https://raw.githubusercontent.com/Mirantis/cri-dockerd/master/packaging/systemd/cri-docker.service
        wget https://raw.githubusercontent.com/Mirantis/cri-dockerd/master/packaging/systemd/cri-docker.socket
        sudo mv cri-docker.socket cri-docker.service /etc/systemd/system/
        sudo sed -i -e 's,/usr/bin/cri-dockerd,/usr/local/bin/cri-dockerd,' /etc/systemd/system/cri-docker.service
        sudo systemctl daemon-reload
        sudo systemctl enable cri-docker.service
        sudo systemctl enable --now cri-docker.socket

    - name: 'Install Minikube and Start'
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube
        sudo mv minikube /usr/local/bin/
        sudo minikube start --driver=none --container-runtime=cri-docker

    - name: 'Set up Kubeconfig for Minikube'
      run: |
        mkdir -p $HOME/.kube
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config

    - name: 'Verify Kubernetes Context'
      run: kubectl config current-context

    - name: 'Download Skaffold'
      run: |
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
        chmod +x skaffold
        sudo mv skaffold /usr/local/bin/

    - name: 'Verify Skaffold Installation'
      run: |
        echo "Skaffold location: $(which skaffold)"
        echo "Skaffold file type: $(file /usr/local/bin/skaffold)"
        echo "Skaffold version:"
        skaffold version
        echo "Skaffold help:"
        skaffold --help

    - name: Remove Existing Skaffold Config
      run: |
        if [ -f "skaffold.yaml" ]; then
          rm skaffold.yaml
          echo "Removed existing skaffold.yaml."
        fi

    - name: Skaffold Initialization
      run: skaffold init --skip-build --force

    - name: Build Artifact
      run: skaffold build

    - name: Deploy Artifact
      run: skaffold run